### PR TITLE
Feature/joi config

### PR DESCRIPTION
**Pull request by nickmccally**
Add support for joi, using .env instead of config.js. README.md has been updated to reflect changes that are necessary.

### CODE REVIEW

**Comment by mountHouli** [comment]
This PR should also delete and/or replace file `config.js.docker`, correct?

**Comment by mountHouli** [comment]
What are these `//` comments? Why not use `#`?
```
## MONGO SETTINGS ##
MONGO_SSL=false
// MONGO=mongodb://localhost/orange-api
// ZEROPC=tcp://127.0.0.1:4242
```

**Comment by puckybreg** [comment]
@mountHouli that's a good point. It brings up the larger question of how we plan to push new versions of these apps to our Kubernetes cluster now that the config has to be provided to the docker container at runtime via environment variables. @ElijahGeorge what is the LOE to set these environment variables using our Kubernetes Staging Cluster?

**Comment by mountHouli** [comment]
Also, `TEST_TOKEN` is in `.env` and `.env.example`, but it is nowhere else in the codebase. Should it be removed, or is something wanting it but broken?

**Comment by mountHouli** [comment]
Regarding `config.js.docker`, having looked into it a bit more, the answer to my original question is yes. It's just a question of what additional work needs to be done--to your point @puckybreg.

**Comment by mountHouli** [comment]
1. We decided we're going to do the `config.js.docker` work in a new branch.
2. Nick said he removed `TEST_TOKEN`
3. Nick said `//` works the same as `#`

Therefore, I'll approve this PR.

**Pull request merged**
