### PR TITLE
Hotfix: Enable Plus Sign in Email

### PR DESCRIPTION
**Pull request by mountHouli**
## hotfix/enable-plus-sign-in-email
The "+" sign is now a valid character in email addresses.

## Branch Setup
None.

Note (just for clarity): No changes to the amida-auth-microservice required.

## Related Tickets
* [ORANGE-477](https://jira.amida-tech.com/browse/ORANGE-477)

## Screenshots
N/A

## Test Cases
1. Create a user that has a + sign in the email address. It should work, and, as is the norm for that process, it should also automatically log you in.
2. Login as a user who has a + sign in the email address. It should work.

## Readiness
1. [ N/A ] This PR has full test coverage
2. [ N/A ] This PR passess all tests
3. [ Yes ] This PR has no linting errors
4. [ Yes ] This PR has been updated to include all changes from develop
5. [ Yes ] This PR has been tested in iOS *and* Android
6. [ N/A ] This PR's changes to configration files for an instance's runtime have been documented
7. [ N/A ] This PR's required changes outside of the scope of this repository have been documented in this pull request

### CODE REVIEW

**Comment by mountHouli** [comment]
Note: I talked it over with Jon, and he's cool with this.

**Comment by mountHouli** [comment]
The `orange-api` has automated tests! Cool!

Added.

**Comment by mountHouli** [comment]
@hrickards requested changes are done (added a test).

**Comment by hrickards** [comment]
@nickmccally did you want to review? Otherwise this looks good to me and I am happy to merge.

**Comment by hrickards** [comment]
Merged. I'm not sure of the JIRA workflow we're using for Orange, so @mountHouli can you update the ticket appropriately? Thanks!

**Comment by mountHouli** [comment]
Yup. Thanks.

**Pull request merged**
