### PR TITLE
Fix markdown typo

### PR DESCRIPTION
**Pull request by papac**

### CODE REVIEW

**Comment by hrickards** [comment]
Nice catch, thanks!

**Comment by hrickards** [comment]
@papac just a heads up that we are about to switch the default development branch to `develop` (and follow gitflow methodology)

**Comment by jsachs** [comment]
@hrickards as a sidebar, I think this is a change in how Github-flavored Markdown renders. I've been seeing this pop up in several of our repos. Omitting a space after the hashes used to not be a problem, and now it is.

**Comment by papac** [comment]
@hrickards OK well received.

**Pull request merged**
