### PR TITLE
Feature/orange 206 timezone with dates

### PR DESCRIPTION
**Pull request by dbrezack**
Adds timezone to doses and events

https://jira.amida-tech.com/browse/ORANGE-206

Don't forget to `yarn install`

### CODE REVIEW

**Comment by B3rry** [comment]
@dbrezack to re-merge
@puckybreg and @orndorffgrant to re-review this sprint

**Comment by orndorffgrant** [comment]
I created a ticket in JIRA for updating the frontend to work with this: https://jira.amida-tech.com/browse/ORANGE-669

**Comment by orndorffgrant** [comment]
@dbrezack I'm working on updating the frontend code for this. I just created a journal entry and sent this date:

```
date: {
  utc: '2018-08-15T18:32:28.598Z',
  timezone: 'America/New_York'
}
```

It succeeded, but sent back as a response this date

```
date: {
  utc: '2018-08-15T14:32:28.598-04:00',
  timezone: 'America/New_York'
}
```

which is the right time, but includes the offset in the iso string of the field called `utc`. I would expect it to be returned in utc time with no offset. What do you think?

**Comment by dbrezack** [comment]
@orndorffgrant This is just how mongo handles dates. I think in the end it doesn't really matter.

**Comment by orndorffgrant** [comment]
@dbrezack Cool, sounds fine to me then - My approval is maintained
@puckybreg @B3rry lets get this and https://github.com/amida-tech/orange-ignite/pull/178 reviewed so we can get this in finally

**Comment by orndorffgrant** [comment]
Today is the 100th day this PR has been open! 🎉(?) 
I think it can be merged. @B3rry ?
@puckybreg as soon as the frontend PR associated with this is merged (https://github.com/amida-tech/orange-ignite/pull/178) we'll need to push this update to staging or else things will break.

**Pull request merged**
