### PR TITLE
[ORANGE-1166] hotfix/yarn-test-stop-drop-db

### PR DESCRIPTION
**Pull request by mountHouli**
# Related Tickets

- [ORANGE-1166](https://jira.amida.com/browse/ORANGE-1166)

# Other Repos' PR(s) Intended to Work With This PR

None.

# How Things Worked (or Didn't) Before This PR

See Jira ticket.

# How Things Works Now (And How to Test)

For background, see Jira ticket.

To test: `yarn test` and `grunt test`.

For what should happen when you `yarn test` or `grunt test`, see skip down to the PR conversation below (before reading the next paragraph).

If you `yarn test` or `grunt test` and NODE_ENV !== "test", it should abort before dropping the database, so as to not accidentally use something other than `.env.test` and thereby accidentally drop the wrong database. This safety check was added as a failsafe, even though there is no way to set NODE_ENV to anything other than "test", except by editing the following portion of the gruntfile:
```
        env: {
            test: {
                NODE_ENV: "test"
            }
        },
```

# Readiness

1. [N/A] This PR has full test coverage (If this PR fixes a bug, you _must_ add test cases respresentative of the bug).
2. [As much as the base branch does] This PR passes all automated tests.
3. [x] This PR has no linting errors.
4. [x] This PR has no hardcoded UI strings or other obvious issues.
5. [x] This PR has been updated to include all changes from develop.
6. [N/A] This PR's changes to configuration files have been documented in all appropriate places (such as but not limited to README.md), if applicable.
7. [N/A] This PR's required changes outside of the scope of this repository have been documented in this pull request.

### CODE REVIEW

**Comment by mountHouli** [comment]
@dbrezack Yeah, I addressed one problem, but the more I reflect on it, the solution is not ideal.

I suppose solution for `yarn test` should be:

- It should definitely use `.env.test`. This is not currently a problem, as `yarn test` does indeed use `.env.test`. I'm just stating it here because
  - `grunt test` unfortunately does not define `NODE_ENV=test`, so it doesn't use `.env.test`, so it drops the database you have listed in `.env`. But to be clear, that's unrelated to `yarn test`.
  - The proposed algorithm below will drop your database, so it better be the right one.
1. Check if the DB exists, and if it does, delete it.
2. Create the DB
3. Run the tests
4. Delete the DB no matter what

What do you think?

**Comment by dbrezack** [comment]
@mountHouli Yup that sounds like it would generally fix more situations. 

Something along the lines of 
`npm run delete_db || npm run check_test_db && cross-env NODE_ENV=test grunt test || npm run delete_db`

**Comment by mountHouli** [comment]
I implemented this algorithm for both `grunt test` and `yarn test`, while also cleaning up and simplifying things significantly:

1. Ensure `NODE_ENV==='test'` and abort if not.
2. Delete the DB.
3. Run the tests.
4. Delete the DB. <= Unfortunately, `grunt test`, if aborted, will not run this step. However, it doesn't really matter because step 2 always runs.

**Comment by mountHouli** [comment]
I decided to get rid of step 4 of the aforementioned process because getting grunt to reliably run it was difficult, and it's not necessary anyway, as step 2 always runs.

**Pull request merged**
