### PR TITLE
Feature/loadtest

### PR DESCRIPTION
**Pull request by jsachs**
Instructions from README on how to go about using the load-testing script

## Load Testing

SSH Tunnel into the remote machine where `orange-api` has been deployed and from where you will be installing Locust and running your load tests. The following command will create an SSH tunnel into the specified address and begin forwarding your machine's local port `8089` (making a 'tunnel' with the remote machine's port `8089`) so that you can run the load tests on the server and still view the locust web interface from your local machine.

`ssh  -L 8089:localhost:8089 user@example.com`

### Installing Locust and other Python Dependencies 

Once you have SSH'd into your remote machine, you will do the following on that machine to install the necessary libraries to run the load test script:

Create a new virtual enviroment using virtualenv with the command:

`virtualenv env`

I have called mine `env`.
(If you do not have virtualenv installed you can install it using `pip install virtualenv`) 

activate your new enviroment with the command

`source env/bin/activate` 

Once inside your new enviroment you will need to install locust, faker, and arrow using the following commands

`pip install locustio`

`pip install faker`

`pip install arrow`

### Launching load test using Locust

On the remote machine, navigate inside the directory that holds the orange-api repository and contains the file `locustfile.py`

Launch locust
`locust -f locustfile.py -H "http://localhost:5000/v1"` 

### Viewing Locust web interface

Now, on your local machine:

Point your browser to http://127.0.0.1:8089/ 

From the Locust web interface you can change the settings and run the load-test

### CODE REVIEW

**Comment by jsachs** [comment]
@puckybreg can you add instructions for running the load tests to the README, as well as to the PR description?

**Comment by puckybreg** [comment]
@jsachs will do!

**Comment by jsachs** [comment]
@puckybreg this needs a bit more installation information for locust. For example, instructions (or a script) to set up a virtualenv with locust and all of its dependencies, such as faker and arrow.

**Comment by jsachs** [comment]
@puckybreg how long does it take to initialize? I see the following lines:
```
[2017-07-07 15:16:42,109] eschaton.local/INFO/locust.main: Starting web monitor at *:8089
[2017-07-07 15:16:42,110] eschaton.local/INFO/locust.main: Starting Locust 0.7.5
```
yet I cannot visit the application at localhost:8089

**Comment by puckybreg** [comment]
I will update the instructions with details on installing the dependent libraries. As for the issues you are running into with the port forwarding it is not giving you any errors until you check the ssh process?

**Pull request merged**
